services:
  backend:
    build: ./backend
    container_name: mvp_backend
    ports:
      - '3001:3001'
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge