services:
  backend:
    build: ./backend
    container_name: colab_backend_c
    ports:
      - '8080:8080'
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge